buildTrain:
	g++ train.cpp utils.cpp -o train -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -Wall -std=c++11

buildScore:
	g++ score.cpp utils.cpp -o score -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -Wall -std=c++11

clean:
	rm -rf train score

cleanTrainData:
	rm -rf mlp.yaml vocabulary.yaml
